export const themes = [
  {
    name: "Azul",
    headerColor: "#3b82f6",
    textColor: "#ffffff",
  },
  {
    name: "Púrpura",
    headerColor: "#8b5cf6",
    textColor: "#f8fafc",
    sidebarColor: "#5b21b6",
    hoverColor: "#6d28d9",
  },
  {
    name: "Amarillo",
    headerColor: "#facc15",
    textColor: "#fef2f2",
    sidebarColor: "#a16207",
    hoverColor: "#ca8a04",
  },
  {
    name: "Naranja",
    headerColor: "#fb923c",
    textColor: "#f8fafc",
    sidebarColor: "#c2410c",
    hoverColor: "#ea580c",
  },
  {
    name: "Rojo",
    headerColor: "#ef4444",
    textColor: "#fef2f2",
    sidebarColor: "#991b1b",
    hoverColor: "#b91c1c",
  },
  {
    name: "Verde",
    headerColor: "#22c55e",
    textColor: "#fef2f2",
    sidebarColor: "#166534",
    hoverColor: "#15803d",
  },
  {
    name: "Rosa",
    headerColor: "#ec4899",
    textColor: "#fdf2f8",
    sidebarColor: "#9d174d",
    hoverColor: "#be185d",
  },
  {
    name: "Turquesa",
    headerColor: "#2dd4bf",
    textColor: "#fef2f2",
    sidebarColor: "#115e59",
    hoverColor: "#0f766e",
  },
  {
    name: "Rojo Oscuro",
    headerColor: "#f43f5e",
    textColor: "#fff1f2",
    sidebarColor: "#881337",
    hoverColor: "#9f1239",
  },
  {
    name: "Cyan",
    headerColor: "#22d3ee",
    textColor: "#fef2f2",
    sidebarColor: "#164e63",
    hoverColor: "#0e7490",
  },
];